version: "3.8"

networks:
  corp:
    driver: bridge

services:
  next-client:
    container_name: next-client
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy    
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/variable.conf:/etc/nginx/variable.conf