version: "3.8"

networks:
  corp:
    driver: bridge

services:
  nginx_proxy:
    container_name: nginx_proxy   
    build:
      context: ./nginx
    ports:
      - 80:80

  next-client:
    container_name: next-client
    build:
      context: ./next-homepage
    ports:
      - 3000:3000
